### ISSUE TITLE
Bug in mergeWithNextNode private function

### ISSUE THREAD

**Issue by iskolbin** [l-tamas/Unrolled-linked-list#1]
I think line 943 is wrong. The source looks like:

940        if (next.next != null) {
941            next.next.previous = node;
942       }
943        node.next = next.next.next;

It's obvious that should be:

943 node.next = next.next;

**Comment by Scusemua** [comment]
Yes, this is definitely incorrect.

Line 943 should be:

node.next = next.next;

Currently you end up skipping over a perfectly good node.

**Comment by l-tamas** [comment]
Fixed by #2. Thank you both!
